// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcogccusyerkvoimfxeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjb2djY3VzeWVya3ZvaW1meGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0ODgwMjUsImV4cCI6MjA4NDA2NDAyNX0.utFfYHcIOmxNP7fR27fGtECZz-BXZiqN-oKUMHLGq24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});